# Generated by Django 5.0.3 on 2024-03-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=255)),
                ('colonia', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metros_cuadrados', models.IntegerField()),
                ('imagen_url', models.ImageField(upload_to='static/imagenes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Inmueble',
        ),
    ]
