# Generated by Django 5.0.3 on 2024-03-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatas', '0002_propiedad_delete_inmueble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_url',
            field=models.CharField(max_length=255),
        ),
    ]
