# Generated by Django 5.0.3 on 2024-05-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatas', '0003_alter_propiedad_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrenos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calle2', models.CharField(max_length=255)),
                ('colonia2', models.CharField(max_length=255)),
                ('estado2', models.CharField(max_length=255)),
                ('pais2', models.CharField(max_length=255)),
                ('ciudad2', models.CharField(default='Sin especificar', max_length=100)),
                ('descripcion2', models.TextField(default='Sin especificar')),
                ('precio2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metros_cuadrados2', models.IntegerField()),
                ('imagen_url2', models.CharField(max_length=255)),
            ],
        ),
    ]
