# Generated by Django 5.0.3 on 2024-05-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatas', '0004_terrenos'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(default='Sin especificar'),
        ),
    ]
