# Generated by Django 5.0.3 on 2024-05-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatas', '0005_propiedad_ciudad_propiedad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='imagenes_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
