# Generated by Django 5.0.3 on 2024-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatas', '0006_propiedad_imagenes_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrenos',
            name='imagenes_urls2',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
