# Generated by Django 5.0.3 on 2024-06-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatas', '0007_terrenos_imagenes_urls2'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='banos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cuartos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='habitacion',
            field=models.IntegerField(default=1),
        ),
    ]
